#!/usr/bin/env bash
ln -f x86/{*.ml{,i},libmincaml.S} .
cd test; ln -sf x86/{,too}manyargs.ml .; cd ..
cd shootout; ln -f x86/Makefile .; cd ..
cd bytemark; ln -sf x86/Makefile .; cd ..
cd min-rt; ln -f x86/globals.s .; cd ..
