#!/bin/sh

usage () {
  echo "Usage:"
  echo "    $0 filename.ml"
}

filename=$1
output_asm="${filename%.*}".s
output_exe="${filename%.*}".exe

dune exec bin/min_caml.exe $1 && \
  gcc -m32 -O2 -lm stub/stub.c stub/libmincaml.S $(pwd)/${output_asm} -o $(pwd)/${output_exe}
